baseURL = "https://thehiddenport.dev/"
languageCode = "en-us"
title = "The Hidden Port"
theme = "PaperMod"

[taxonomies]
  tag = "tags"
  category = "categories"

[deployment]
  [[deployment.targets]]
    name = "github"
    url = "https://thehiddenport.dev"

[params]
  description = "The Hidden Port is a blog about cloud security, automation, compliance, and best practices. Learn how to protect your AWS accounts and infrastructure, the right way."
  defaultTheme = "dark"
  disableThemeToggle = true
  enableCDN = false
  securityHeaders = true
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  disableScrollToTop = false
  ShowTaxonomies = true
  enableRobotsTXT = true
  injectHead = true
  author = ["Javier Pulido"]

  [params.seo]
    canonicalURL = true
    twitterCard = "summary_large_image"
    image = "/images/default-preview.png"
    title = "The Hidden Port"
    description = "The Hidden Port is a blog about cloud security, automation, compliance, and best practices. Learn how to protect your AWS accounts and infrastructure, the right way."

  [params.assets]
    favicon = "/favicon.png"

  [params.homeInfoParams]
    Title = "Welcome to The Hidden Port"
    Content = "Cloud Security, Automation, Best Practices, and Beyond."

  [params.home]
    enable = true
    type = "posts"
    subtitle = "Cybersecurity • Cloud • Compliance"
    description = "Security • Cloud • Infra • Thoughts from a hidden terminal"
    typingDelay = 100

    [params.home.avatar]
      enable = true
      src = "images/avatar.png"
      size = "medium"

    [params.home.posts]
      enable = true
      style = "card"  # Force card layout (if FixIt supports it)
      imagePreview = true  # Show post thumbnails
      paginate = 2
      showDate = true  # Display publish date
      showTags = true  # Show tags below titles

    [params.home.signature]
      enable = true
      text = "Trust but verify."

  [params.page.share]
    enable = true
    Twitter = true
    Linkedin = true
    HackerNews = true
    Reddit = true
    Facebook = false
    Whatsapp = false

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/fpulidov"

    [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/ejher"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  
  [[menu.main]]
    name = "Resources"
    url = "/resources/"
    weight = 3

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 30

[pagination]
  pagerSize = 10

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["txt"]

[outputFormats.Robots]
  mediaType = "text/plain"
  baseName = "robots"
  isPlainText = true
  notAlternative = true
  permalinkable = true

[outputFormats.404]
  mediaType = "text/html"
  baseName = "404"
  isHTML = true
  permalinkable = false

[outputs]
  home = ["HTML", "RSS", "JSON", "Robots"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  page = ["HTML"]
  404 = ["HTML"]

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"